version: '3.1'

services:
    db:
        image: postgres:latest
        container_name: gamification_db
        restart: unless-stopped
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
        ports:
            - "${DB_PORT}:5432"
        volumes:
            - gamification_db:/var/lib/postgresql/data
        networks:
            gamification-network:
                aliases:
                    - gamification-network-db

    webserver:
        image: nginx:alpine
        container_name: gamification_webserver
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - gamification-network
        restart: unless-stopped
        tty: true
        ports:
            - "${DOCKER_NGINX_HTTP_PORT}:80"
            - "${DOCKER_NGINX_HTTPS_PORT}:443"

    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: gamification_app
        networks:
            - gamification-network
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

volumes:
    gamification_db:


networks:
    gamification-network:
